Move purchase to pkg ticketbuyer
decred/dcrticketbuyer pull request #70
Opened 2016-10-21 16:53 UTC by tuxcanfly

Refactored to move the purchase logic to a new reusable pkg.

2016-11-10 21:45 UTC, alexlyp commented
not sure all the logic is correct:
21:42:42 2016-11-10 [DBG] TKBY: Current spendable balance at height 202863 for account 'default': 25445.61588345 Coin
21:42:42 2016-11-10 [TRC] TKBY: Current balance 2544561588345 is greater than estimated balance: 0

2016-11-10 22:14 UTC, alexlyp requested changes
So just a couple of basic tweaks to the code I commented on that need to be fixed.

The major thing I noticed is that you've ripped out all of the csv updating but left the webui implementation.  Obviously we don't necessarily want that to be used with dcrwallet, but now you've stopped supporting things that previously worked in ticketbuyer.  

If you plan on ripping out all the httpsvr stuff, then remove it all and note it.  Don't leave some and just stop updating the csvs.  People will get really confused.  

In my opinion, ticketbuyer should work exactly how it does now, just with the ticketbuyer package exported for use elsewhere.

2016-11-10 22:14 UTC, alexlyp commented on ticketbuyer/buyer.go
> -	balEstimated := atomic.LoadInt64(&glBalance)
since you removed this you should probably replace with t.balEstimated = some initial balance.  My comment above refers to this.  "estimated: 0"

2016-11-10 22:14 UTC, alexlyp commented on main.go
> +	purchaser, err := ticketbuyer.NewTicketPurchaser(&ticketbuyer.Config{
i'd rather you make a ticketCfg := ticketbuyer.Config and pass that in as an arg

2016-11-30 17:20 UTC, alexlyp commented
It's currently not updating webui when new blocks connect.

Current block height is 217093, but still sitting at 217069 on :8000

2016-12-01 19:26 UTC, tuxcanfly commented
@alexlyp Thanks for catching that. Looks like the global for height was not being set and that lead to duplicate rows in the csv with the old height.

I have refactored to do away with the globals and instead use a file to read and write the shared data. Removed the unnecessary atomics and mutexes which were not being used properly in the first place.

My initial tests seem to suggest that the webui and csv bits are working as before. Will be running some more tests.

Also, I think it would be better to break this PR down into two for easier review. One to deal with the preparation leading up to the refactor (without any functional changes) and one for the new pkg refactor itself. Let me know if that would help.

Thanks.

2016-12-19 14:49 UTC, tuxcanfly commented
This has been implemented in https://github.com/decred/dcrwallet/pull/374

2016-12-19 14:49 UTC, closed without merging